# Centos7 / Py3 / Jupyter
# name py3rjup

FROM mladd/analytics:v1

RUN conda install -c conda-forge tweepy wordcloud xgboost r-kernlab
RUN conda install -c conda-forge glpk
RUN conda install -c anaconda-cluster click
#RUN conda install -c conda-forge r-party 






