users: docker/build-push-action@v1
with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}
    repository: mjladd/Dockerfiles
    tags: latest

name: build and push images
on:
    push:
        branches:
        - master
        paths:
        - "*"
        - "!README.md"


